# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-10 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pugio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='moneda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moneda', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Monedas',
            },
        ),
    ]
