# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-10 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pugio', '0002_moneda'),
    ]

    operations = [
        migrations.CreateModel(
            name='impuesto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('impuesto', models.CharField(max_length=25)),
                ('porcentaje', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'verbose_name_plural': 'Impuestos',
            },
        ),
    ]
