# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-15 12:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pugio', '0003_impuesto'),
    ]

    operations = [
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('codigopostal', models.CharField(blank=True, max_length=10, null=True)),
                ('pais', models.CharField(blank=True, default='Espana', max_length=25, null=True)),
                ('cif', models.CharField(blank=True, max_length=20, null=True)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('movil', models.CharField(blank=True, max_length=15, null=True)),
                ('fax', models.CharField(blank=True, max_length=15, null=True)),
                ('mail', models.EmailField(blank=True, max_length=125)),
                ('fecha_alta', models.DateField(blank=True, default=datetime.datetime.now)),
                ('baja', models.BooleanField(default=True)),
                ('fecha_baja', models.DateField(blank=True, default=datetime.datetime.now)),
                ('poblacion', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='pugio.poblacion')),
                ('provincia', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='pugio.provincia')),
            ],
        ),
    ]
