# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-15 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pugio', '0005_auto_20170315_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='baja',
            field=models.BooleanField(default=False),
        ),
    ]
