# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-16 15:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pugio', '0007_empresa'),
    ]

    operations = [
        migrations.CreateModel(
            name='departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departamento', models.CharField(max_length=75)),
            ],
            options={
                'verbose_name_plural': 'Departamentos',
            },
        ),
        migrations.CreateModel(
            name='empleado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=75)),
                ('apellidos', models.CharField(max_length=75)),
                ('direccion', models.CharField(max_length=150)),
                ('cp', models.CharField(blank=True, max_length=10, null=True)),
                ('pais', models.CharField(blank=True, default='Espana', max_length=50, null=True)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('movil', models.CharField(blank=True, max_length=15, null=True)),
                ('mail', models.EmailField(blank=True, max_length=125)),
                ('fotografia', models.ImageField(blank=True, upload_to='imagenes')),
                ('nif', models.CharField(max_length=15)),
                ('nss', models.CharField(max_length=50)),
                ('departamento', models.ForeignKey(blank=None, default=None, on_delete=django.db.models.deletion.CASCADE, to='pugio.departamento')),
            ],
            options={
                'verbose_name_plural': 'Empleados',
            },
        ),
        migrations.AddField(
            model_name='empresa',
            name='pais',
            field=models.CharField(blank=True, default='Espana', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='empresa',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='pugio.empresa'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='poblacion',
            field=models.ForeignKey(blank=None, default=None, on_delete=django.db.models.deletion.CASCADE, to='pugio.poblacion'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='provincia',
            field=models.ForeignKey(blank=None, default=None, on_delete=django.db.models.deletion.CASCADE, to='pugio.provincia'),
        ),
    ]
