# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-16 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pugio', '0008_auto_20170316_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='apellidos',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
