# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-17 12:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pugio', '0009_cliente_apellidos'),
    ]

    operations = [
        migrations.CreateModel(
            name='sucursal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sucursal', models.CharField(default=None, max_length=50)),
                ('direccion', models.CharField(max_length=100)),
                ('codigopostal', models.CharField(blank=True, max_length=10, null=True)),
                ('pais', models.CharField(blank=True, default='Espana', max_length=25, null=True)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('movil', models.CharField(blank=True, max_length=15, null=True)),
                ('fax', models.CharField(blank=True, max_length=15, null=True)),
                ('mail', models.EmailField(blank=True, max_length=125)),
                ('responsable', models.CharField(blank=True, max_length=75, null=True)),
                ('empresa', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='pugio.empresa')),
                ('poblacion', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='pugio.poblacion')),
                ('provincia', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='pugio.provincia')),
            ],
            options={
                'verbose_name_plural': 'Sucursales',
            },
        ),
        migrations.AddField(
            model_name='cliente',
            name='empresa',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='pugio.empresa'),
        ),
        migrations.AddField(
            model_name='departamento',
            name='empresa',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='pugio.empresa'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='sucursal',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='pugio.sucursal'),
        ),
        migrations.AddField(
            model_name='departamento',
            name='sucursal',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='pugio.sucursal'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='sucursal',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='pugio.sucursal'),
        ),
    ]
