# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-21 10:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pugio', '0010_auto_20170317_1335'),
    ]

    operations = [
        migrations.CreateModel(
            name='pago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default=None, max_length=50)),
                ('dia_1', models.PositiveIntegerField(blank=True, null=True)),
                ('dia_2', models.PositiveIntegerField(blank=True, null=True)),
                ('dia_3', models.PositiveIntegerField(blank=True, null=True)),
                ('dia_4', models.PositiveIntegerField(blank=True, null=True)),
                ('dia_5', models.PositiveIntegerField(blank=True, null=True)),
                ('dia_6', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Pagos',
            },
        ),
        migrations.CreateModel(
            name='proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(default=None, max_length=100)),
                ('cif', models.CharField(max_length=15)),
                ('direccion_social', models.CharField(max_length=150)),
                ('cp_social', models.CharField(blank=True, max_length=10, null=True)),
                ('pais_social', models.CharField(blank=True, default='Espana', max_length=50, null=True)),
                ('telefono_social', models.CharField(blank=True, max_length=15, null=True)),
                ('movil_social', models.CharField(blank=True, max_length=15, null=True)),
                ('fax_social', models.CharField(blank=True, max_length=15, null=True)),
                ('mail_social', models.EmailField(blank=True, max_length=125)),
                ('web', models.URLField(blank=True, max_length=150)),
                ('logotipo', models.ImageField(blank=True, upload_to='imagenes')),
                ('nombre_comercial', models.CharField(max_length=100)),
                ('direccion_comercial', models.CharField(max_length=150)),
                ('cp_comercial', models.CharField(blank=True, max_length=10, null=True)),
                ('pais_comercial', models.CharField(blank=True, default='Espana', max_length=50, null=True)),
                ('telefono_comercial', models.CharField(blank=True, max_length=15, null=True)),
                ('movil_comercial', models.CharField(blank=True, max_length=15, null=True)),
                ('fax_comercial', models.CharField(blank=True, max_length=15, null=True)),
                ('mail_comercial', models.EmailField(blank=True, max_length=125)),
                ('portal', models.URLField(blank=True, max_length=150)),
                ('fecha_alta', models.DateField(blank=True, default=datetime.datetime.now)),
                ('baja', models.BooleanField(default=False)),
                ('fecha_baja', models.DateField(blank=True, default=datetime.datetime.now)),
                ('persona_contacto', models.CharField(blank=True, max_length=50, null=True)),
                ('telefono_contacto', models.CharField(blank=True, max_length=15, null=True)),
                ('mail_contacto', models.EmailField(blank=True, max_length=125)),
                ('observaciones', models.CharField(blank=True, max_length=255, null=True)),
                ('empresa', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='pugio.empresa')),
                ('impuesto', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='pugio.impuesto')),
                ('pago', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='pugio.pago')),
                ('poblacion_comercial', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='poblacion_c', to='pugio.poblacion')),
                ('poblacion_social', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='pugio.poblacion')),
                ('provincia_comercial', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='provincia_c', to='pugio.provincia')),
                ('provincia_social', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='pugio.provincia')),
            ],
            options={
                'verbose_name_plural': 'Proveedores',
            },
        ),
        migrations.AddField(
            model_name='empleado',
            name='baja',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='empleado',
            name='fecha_alta',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='empleado',
            name='fecha_baja',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
