# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-29 11:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pugio', '0011_auto_20170321_1141'),
    ]

    operations = [
        migrations.CreateModel(
            name='familia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letra', models.CharField(max_length=2)),
                ('nombre', models.CharField(max_length=70)),
            ],
            options={
                'verbose_name_plural': 'Familias',
            },
        ),
        migrations.CreateModel(
            name='subfamilia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letra', models.CharField(max_length=2)),
                ('nombre', models.CharField(max_length=70)),
                ('familia', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='pugio.familia')),
            ],
            options={
                'verbose_name_plural': 'SubFamilias',
            },
        ),
    ]
