# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-29 14:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pugio', '0012_familia_subfamilia'),
    ]

    operations = [
        migrations.CreateModel(
            name='catalogo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default=None, max_length=70)),
                ('fecha_alta', models.DateField(blank=True, default=datetime.datetime.now)),
                ('baja', models.BooleanField(default=False)),
                ('fecha_baja', models.DateField(blank=True, default=datetime.datetime.now)),
            ],
            options={
                'verbose_name_plural': 'Catalogos',
            },
        ),
        migrations.CreateModel(
            name='condicion_compra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descuento_1', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('descuento_2', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('descuento_3', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('descuento_4', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('descuento_5', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('cargo_1', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('cargo_2', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('cargo_3', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('fecha_alta', models.DateField(blank=True, default=datetime.datetime.now)),
                ('baja', models.BooleanField(default=False)),
                ('fecha_baja', models.DateField(blank=True, default=datetime.datetime.now)),
                ('pago', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='pugio.pago')),
                ('proveedor', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='pugio.proveedor')),
            ],
            options={
                'verbose_name_plural': 'Condiciones de compra',
            },
        ),
        migrations.CreateModel(
            name='condicion_marcaje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('margen', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('fecha_alta', models.DateField(blank=True, default=datetime.datetime.now)),
                ('baja', models.BooleanField(default=False)),
                ('fecha_baja', models.DateField(blank=True, default=datetime.datetime.now)),
                ('impuesto', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='pugio.impuesto')),
                ('proveedor', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='pugio.proveedor')),
            ],
            options={
                'verbose_name_plural': 'Condiciones de Marcaje',
            },
        ),
        migrations.AddField(
            model_name='catalogo',
            name='condicion_compra',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='pugio.condicion_compra'),
        ),
        migrations.AddField(
            model_name='catalogo',
            name='condicion_marcaje',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='pugio.condicion_marcaje'),
        ),
        migrations.AddField(
            model_name='catalogo',
            name='proveedor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='pugio.proveedor'),
        ),
    ]
