# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-31 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pugio', '0015_almacen'),
    ]

    operations = [
        migrations.AddField(
            model_name='almacen',
            name='direccion',
            field=models.CharField(default=' ', max_length=150),
        ),
    ]
